on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pretend build
      env:
        # if we have an input sha, use that. Otherwise, use the GH sha.
        # This accounts for us being called on a branch, from main, or from a comment on a branch
        SHA: ${{ inputs.sha || github.sha }}
      run: |
        packageVersionSuffix=${GITHUB_RUN_NUMBER}.${SHA::7}
        echo $packageVersionSuffix
