name: Stage-gates-main
concurrency:
  group: stage-gates-main-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/wf-build.yaml
    with:
      artifact_name: app

  # deploy-dev:
  #   needs: build
  #   uses: ./.github/workflows/wf-deploy.yaml
  #   with:
  #     artifact_name: app
  #     environment_name: dev

  # deploy-preprod:
  #   needs: deploy-dev
  #   uses: ./.github/workflows/wf-deploy.yaml
  #   with:
  #     artifact_name: app
  #     environment_name: preprod

  # deploy-prod:
  #   needs: deploy-preprod
  #   uses: ./.github/workflows/wf-deploy.yaml
  #   with:
  #     artifact_name: app
  #     environment_name: prod

  debug:
    name: Debug
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: eg
          path: ./

      - name: Trigger repository dispatch event
        uses: actions/github-script@v6
        with:
          script: |

            const listArtifacts = github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: 5804107797
            });

            console.log(JSON.stringify(listArtifacts, null, 2));

# const artifactResponse = github.rest.actions.getArtifact({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   artifact_id: 0
# });

# console.log(JSON.stringify(artifactResponse, null, 2));
