name: Stage-gates-main
concurrency:
  group: stage-gates-main-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/wf-build.yaml
    with:
      artifact_name: app

  # deploy-dev:
  #   needs: build
  #   uses: ./.github/workflows/wf-deploy.yaml
  #   with:
  #     artifact_name: app
  #     environment_name: dev

  # deploy-preprod:
  #   needs: deploy-dev
  #   uses: ./.github/workflows/wf-deploy.yaml
  #   with:
  #     artifact_name: app
  #     environment_name: preprod

  # deploy-prod:
  #   needs: deploy-preprod
  #   uses: ./.github/workflows/wf-deploy.yaml
  #   with:
  #     artifact_name: app
  #     environment_name: prod

  debug:
    name: Debug
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: fetch-artefacts
        with:
          result-encoding: string
          script: |
            const script = require('./.github/workflows/fetch-artefacts.js');
            await script({github, context, fetch, runId: 5804107797});

      - name: ls
        run: |
          ls -la
          echo ${{ steps.fetch-artefacts.outputs.result }}

      - uses: actions/github-script@v6
        with:
          script: |
            const workflowRun = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: 5804107797
            });

            console.log(workflowRun);

# const resultThisRun = await github.request(`https://api.github.com/repos/${context.repo.owner}/${context.repo.repo}/actions/runs/${{ github.run_id }}/artifacts`);
# console.log(resultThisRun);

# const workflowRuns = await github.paginate(github.rest.actions.getWorkflowRun({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   run_id: 5804107797
# }));

# for (const wr of workflowRuns) {
#   console.log(JSON.stringify(wr, null, 2));
# }

# const listArtifacts = await github.paginate(github.rest.actions.listWorkflowRunArtifacts({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   run_id: 5804107797
# }));

# for (const art of listArtifacts) {
#   console.log(JSON.stringify(art, null, 2));
# }

# const thisListArtifacts = await github.paginate(github.rest.actions.listWorkflowRunArtifacts({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   run_id: ${{ github.run_id }}
# }));

# for (const art of thisListArtifacts) {
#   console.log(JSON.stringify(art, null, 2));
# }

# const artifactResponse = github.rest.actions.getArtifact({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   artifact_id: 0
# });

# console.log(JSON.stringify(artifactResponse, null, 2));
