name: Stage-gates-eg2
concurrency:
  group: stage-gates-eg2-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/wf-build.yaml
    with:
      artifact_name: app

  deploy-dev:
    needs: build
    uses: ./.github/workflows/wf-deploy.yaml
    with:
      artifact_name: app
      environment_name: dev
