name: self-hosted-main
concurrency:
  group: self-hosted-main-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: https://npm.pkg.github.com/
          cache-dependency-path: src/api

      - name: Test, and package
        working-directory: src/api
        run: |
          ls -la
          npm ci
          npm run test
          npm run dist
