on:
  workflow_call:
    inputs:
      artifact_name:
        description: Name of artifact bundle to download
        required: true
        type: string

      environment_name:
        description: "the name of the environment we are deploying to"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
    - uses: actions/checkout@v3

    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ./

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist.zip
        draft: true # by marking this as draft, we are able to "release" it via the GH UI, thereby triggering a deployment
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
