on:
  workflow_call:

jobs:
  dispatch-create-release:
    name: Dispatch create release event
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Trigger repository dispatch event
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "create_release"
            });
