on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of artifact bundle to download.
        required: true
        type: string

      environment_name:
        description: The name of the environment to deploy to.
        required: true
        type: string

jobs:
  deploy:
    name: "Deploy to ${{ inputs.environment_name }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
    - uses: actions/checkout@v3

    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ./

    - name: pretend deploy ${{ inputs.artifact_name }}
      run: |
        echo deploying to ${{ inputs.environment_name }}
        # Show the artifact that we've downloaded from the release:
        ls -la ./

        echo '### Release deployed! 🚀' >> $GITHUB_STEP_SUMMARY
        echo '---' >> $GITHUB_STEP_SUMMARY
        echo $(du -h dist.zip) >> $GITHUB_STEP_SUMMARY
        echo "Environment: ${{ inputs.environment_name }}" >> $GITHUB_STEP_SUMMARY
