on:
  workflow_call:
    inputs:
      artifact_name:
        description: Name of artifact bundle to download
        required: true
        type: string

      environment_name:
        description: "the name of the environment we are deploying to"
        required: true
        type: string

jobs:
  deploy:
    name: "Deploy to ${{ inputs.environment_name }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
    - uses: actions/checkout@v3

    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ./

    - name: pretend deploy ${{ inputs.artifact_name }}
      run: |
        echo deploying to ${{ inputs.environment_name }}
        ls -la ./
